### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by couturerm** [Lecheps/PROGNOS_data#1]
Any way to avoid having to punch our password in cleartext ? This is also our email password ...

**Comment by Lecheps** [comment]
Hi,
You could point to a file containing your username and password, possibly encrypted. I'll eventually fix that. I don't know how to do it off the top of my head.
/JL

Get Outlook for iOS




On Tue, Nov 22, 2016 at 5:54 PM +0100, "Raoul-M Couture" <notifications@github.com> wrote:












Any way to avoid having to punch our password in cleartext ? This is also our email password ...

**Comment by Lecheps** [comment]
Done. Replaced cleartext by interactive input.
